FROM node:25-alpine

WORKDIR /usr/src/app

# Copy dashboard package.json
COPY dashboard/package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy dashboard source
COPY dashboard/ ./

# Expose port
EXPOSE 5173

CMD ["npm", "run", "dev"]
