FROM node:25-alpine

WORKDIR /usr/src/app

# Copy all package.json files for workspaces
COPY package*.json ./
COPY bot/package*.json ./bot/
COPY dashboard/package*.json ./dashboard/
COPY shared/package*.json ./shared/
COPY docs/package*.json ./docs/

# Install dependencies for all workspaces
RUN npm install
RUN apk add --no-cache curl

WORKDIR /usr/src/app/bot
EXPOSE 3000
