FROM node:20-alpine

WORKDIR /usr/src/app

# Copy API package.json
COPY api/package*.json ./api/

# Install dependencies
WORKDIR /usr/src/app/api
RUN npm install

# Expose port
EXPOSE 3000

WORKDIR /usr/src/app/api
CMD ["npm", "start"]
